export const FEATURE_CONFIG = {
  "Age (yrs)": {
    label: "Age",
    unit: "years",
    type: "number",
    min: 15,
    max: 60,
    step: 1,
    placeholder: "Example: 25",
  },
  BMI: {
    label: "Body Mass Index (BMI)",
    type: "number",
    min: 10,
    max: 60,
    step: 0.1,
    placeholder: "Example: 24.5",
  },
  "Cycle(R/I)": {
    label: "Menstrual cycle pattern",
    type: "select",
    options: [
      { label: "Regular", value: 2 },
      { label: "Irregular", value: 4 },
    ],
  },
"Cycle length(days)": {
  label: "Menstrual duration",
  unit: "days",
  type: "number",
  min: 1,
  max: 15,
  step: 1,
  placeholder: "Example: 5",
},
  "Pregnant(Y/N)": {
    label: "Currently pregnant",
    type: "yesNo",
  },
  "No. of aborptions": {
    label: "Previous pregnancy losses",
    type: "number",
    min: 0,
    max: 20,
    step: 1,
    placeholder: "Enter 0 if none",
  },
  "Weight gain(Y/N)": {
    label: "Recent weight gain",
    type: "yesNo",
  },
  "hair growth(Y/N)": {
    label: "Excess facial or body hair growth",
    type: "yesNo",
  },
  "Skin darkening (Y/N)": {
    label: "Skin darkening",
    type: "yesNo",
  },
  "Hair loss(Y/N)": {
    label: "Hair loss",
    type: "yesNo",
  },
  "Pimples(Y/N)": {
    label: "Frequent pimples or acne",
    type: "yesNo",
  },
  "Fast food (Y/N)": {
    label: "Regular fast-food consumption",
    type: "yesNo",
  },
  "Reg.Exercise(Y/N)": {
    label: "Regular exercise",
    type: "yesNo",
  },
  "Pulse rate(bpm)": {
    label: "Pulse rate",
    unit: "bpm",
    type: "number",
    min: 30,
    max: 220,
    step: 1,
    placeholder: "Example: 72",
  },
  "RR (breaths/min)": {
    label: "Respiratory rate",
    unit: "breaths/min",
    type: "number",
    min: 5,
    max: 60,
    step: 1,
    placeholder: "Example: 18",
  },
  "Hb(g/dl)": {
    label: "Haemoglobin",
    unit: "g/dL",
    type: "number",
    min: 3,
    max: 25,
    step: 0.1,
    placeholder: "Example: 12.5",
  },
  "BP _Systolic (mmHg)": {
    label: "Systolic blood pressure",
    unit: "mmHg",
    type: "number",
    min: 50,
    max: 250,
    step: 1,
    placeholder: "Example: 120",
  },
  "BP _Diastolic (mmHg)": {
    label: "Diastolic blood pressure",
    unit: "mmHg",
    type: "number",
    min: 30,
    max: 150,
    step: 1,
    placeholder: "Example: 80",
  },
};

export const EXAMPLE_PATIENT = {
  "Age (yrs)": 25,
  "BMI": 24.5,
  "Cycle(R/I)": 2,
  "Cycle length(days)": 5,
  "Pregnant(Y/N)": 0,
  "No. of aborptions": 0,
  "Weight gain(Y/N)": 0,
  "hair growth(Y/N)": 0,
  "Skin darkening (Y/N)": 0,
  "Hair loss(Y/N)": 0,
  "Pimples(Y/N)": 0,
  "Fast food (Y/N)": 0,
  "Reg.Exercise(Y/N)": 1,
  "Pulse rate(bpm)": 72,
  "RR (breaths/min)": 18,
  "Hb(g/dl)": 12.5,
  "BP _Systolic (mmHg)": 120,
  "BP _Diastolic (mmHg)": 80,
};